### ISSUE TITLE
Is th.flurw from xtheadfmemidx really supported on RV32?

### ISSUE THREAD

**Issue by topperc** [XUANTIE-RV/thead-extension-spec#49]
The xtheadfmemidx doc says "All instructions are available for RV32 and RV64". But th.flurw seems identical to th.flrw on RV32.

I found this patch that removed some of the "u" instructions from RV32 for xtheadmemidx. https://github.com/T-head-Semi/thead-extension-spec/commit/5d38f4f87a1ebe297e60c3c5944cdc527b8e3e88

**Comment by cmuellner** [comment]
We should drop `th.flurw` from RV32, just like we did with `th.lur*` and `th.sur*` in the referenced change for the XTheadMemidx extension. The whole table in the XTheadFMemIdx seems to be incorrect and deserves a rework.

Afaik, there is no implementation of XTheadFMemIdx in any of T-Head's RV32 cores. The E902 and the E906 only implement XTheadCmo and XTheadSync. So we can safely edit the spec (and all implementations that follow) without worrying too much.
